const data = [
  {
    id: 1,
    category: "uiux",
    image: "Image1",
    title: "Meetly",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 2,
    category: "frontend",
    image: "Image2",
    title: "CobraCases",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 3,
    category: "frontend",
    image: "Image3",
    title: "Portfolio Website",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 4,
    category: "uiux",
    image: "Image4",
    title: "Reggy",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 5,
    category: "uiux",
    image: "Image5",
    title: "NFT Full Stack Project",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! ",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 6,
    category: "frontend",
    image: "Image6",
    title: "English PhraseCamp Fullstack Blog Website",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 7,
    category: "frontend",
    image: "Image7",
    title: "Spotify Clone",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 8,
    category: "frontend",
    image: "Image8",
    title: "Cars Website",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 9,
    category: "frontend",
    image: "Image9",
    title: "AI Teacher Full Stack Project",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
];
export default data;
